# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Setting
      run: |
        terraform init
        export az_subscription_id=${{ secrets.az_subscription_id }}
        export az_client_id=${{ secrets.az_client_id }}
        export az_client_secret=${{ secrets.az_client_secret }}
        export az_tenant_id=${{ secrets.az_tenant_id }}
        terraform plan
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Train NLU data
      run: |
        wget ${{ secrets.NLU_FILE_PATH }} -P ~
        python tests/test_KoELECTRA_backbone.py
        
